#Configuration data source (Setting for DB)
spring:
  datasource:
    hikari:
      driver-class-name:
    url:
    username:
    password:

#Confuguration Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

#To make the HTTP methods works (PUT,PATCH,DELETE)
  mvc:
    hiddenmethod:
      filter:
        enabled: true
