CREATE TABLE user_list (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "password" varchar NOT NULL,
    "role" varchar NOT NULL,
    CONSTRAINT user_list_pkey PRIMARY KEY (id)
);

CREATE TABLE sensor (
id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
"name" varchar(30) NOT NULL,
CONSTRAINT sensor_pkey PRIMARY KEY (id),
CONSTRAINT uniq UNIQUE (name)
);

CREATE TABLE measurements (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    value numeric NOT NULL,
    raining bool NOT NULL,
    "time" timestamp NOT NULL,
    sensor_id int4 NOT NULL,
    CONSTRAINT measurements_pkey PRIMARY KEY (id),
    CONSTRAINT measurements_sensor_id_fkey FOREIGN KEY (sensor_id) REFERENCES sensor(id) ON DELETE RESTRICT
);